version: '3.7'

services:
  django_experiment-dev:
    container_name: django_experiment-dev
    restart: always
    build:
      context: ../
      dockerfile: dev/Dockerfile
      
    stdin_open: true
    tty: true
    volumes:
      - "../:/usr/src/app"
    depends_on:
      - django_experiment-postgres-dev
    env_file:
      - ../.env.local

  django_experiment-postgres-dev:
    container_name: django_experiment-postgres-dev
    image: postgres:13
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data_dev:
